export const MENUES = [
  {
    title: "Home",
    url: "/",
  },
  {
    title: "About",
    url: "/about",
  },
  {
    title: "Services",
    url: "/services",
  },
  {
    title: "Contact",
    url: "/contact",
  },
];
export const Company = {
  name: "Gamca Token",
  address: "Islamabad, Pakistan",
  phone: "+92 307 1111999",
  whatsApp: "+923071111999",
  logo: "/logo1.jpg",
  email: "gamcatokenpk@gmail.com",
};
export const AccountDetails = [
  {
    bankName: "UBL",
    accountTitle: "MUHAMMAD SALEEM",
    branchCode: "0406",
    accountNumber: "320448061",
    IBAN: "PK64UNIL0109000320448061",
    imgSrc: "/ubl-logo.png",
  },
  {
    bankName: "MEEZAN BANK",
    accountTitle: "MUHAMMAD SALEEM",
    branchCode: "1271",
    accountNumber: "12710105128787",
    IBAN: "PK07MEZN0012710105128787",
    imgSrc: "/meezan-bank-logo.png",
  },
  {
    bankName: "JazzCash",
    accountTitle: "MUHAMMAD SALEEM",
    branchCode: "",
    accountNumber: "03012571556",
    IBAN: "03012571556",
    imgSrc: "/new-Jazzcash-logo.png",
  },
];

export const GCCountries = [
  {
    name: "Saudi Arabia",
    flag: "https://flagcdn.com/w640/sa.png",
    code: "SA",
    whatsappNumber: "+923071111999",
  },
  {
    name: "United Arab Emirates",
    flag: "https://flagcdn.com/w640/ae.png",
    code: "GB",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Bahrain",
    flag: "https://flagcdn.com/w640/bh.png",
    code: "CA",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Qatar",
    flag: "https://flagcdn.com/w640/qa.png",
    code: "AU",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Kuwait",
    flag: "https://flagcdn.com/w640/kw.png",
    code: "NZ",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Oman",
    flag: "https://flagcdn.com/w640/om.png",
    code: "JP",
    whatsappNumber: "+923071111999",
  },
];

export const PakCities = [
  {
    name: "Karachi",
    flag: "/karachi.png",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Lahore",
    flag: "lahore.png",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Islamabad",
    flag: "islamabad.png",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Multan",
    flag: "multan.png",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Gujranwala",
    flag: "gujranwala.png",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Sialkot",
    flag: "sialkot.png",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Peshawer",
    flag: "peshawer.png",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Rawalpindi",
    flag: "rawalpindi.png",
    whatsappNumber: "+923071111999",
  },
];

export const MedicalCenters = [
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
  {
    name: "Al-Madina Medical Center",
    address: "G-8 Markaz, Islamabad",
    phone: "+923071111999",
    whatsappNumber: "+923071111999",
  },
];

const countryAppointment = ["Pakistan"];
export const country_list = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const countries = [
  "Pakistan",
  "Afghanistan",
  "Bangladesh",
  "India",
  "Nepal",
  "Sri Lanka",
  "Philippines",
  "Indonesia",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "China",
  "South Korea",
  "Japan",
  "Turkey",
  "Egypt",
  "Nigeria",
  "Ethiopia",
  "Kenya",
  "South Africa",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "New Zealand",
  "Brazil",
  "Argentina",
  "Chile",
  "Peru",
  "Mexico",
  "Russia",
  "Ukraine",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Portugal",
  "Greece",
  "Netherlands",
  "Belgium",
];
export const gccCountries = [
  "Saudi Arabia",
  "UAE Dubai",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman Muscat",
];
export const cities = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Peshawar",
  "Multan",
  "Gujranwala",
  "Sialkot",
];
export const paymentMethods = ["JazzCash", "Meezan", "UBL"];
export const genders = ["Male", "Female", "Other"];
export const maritalStatuses = ["Single", "Married"];
export const visaTypes = ["Work Visa", "Family Visa"];
export const positions = [
  "Banking & Finance",
  "Carpenter",
  "Cashier",
  "Electrician",
  "Engineer",
  "General Secretary",
  "Health & Medicine & Nursing",
  "Heavy Driver",
  "IT & Internet Engineer",
  "Leisure & Tourism",
  "Light Driver",
  "Mason",
  "President",
  "Labour",
  "Plumber",
  "Doctor",
  "Family",
  "Steel Fixer",
  "Aluminum Technician",
  "Nurse",
  "Male Nurse",
  "Ward Boy",
  "Shovel Operator",
  "Dozer Operator",
  "Car Mechanic",
  "Petrol Mechanic",
  "Diesel Mechanic",
  "Student",
  "Accountant",
  "Lab Technician",
  "Draftsman",
  "Auto-CAD Operator",
  "Painter",
  "Tailor",
  "Welder",
  "X-ray Technician",
  "Lecturer",
  "A.C Technician",
  "Business",
  "Cleaner",
  "Security Guard",
  "House Maid",
  "Manager",
  "Hospital Cleaning",
  "Mechanic",
  "Computer Operator",
  "House Driver",
  "Driver",
  "Cleaning Labour",
  "Building Electrician",
  "Salesman",
  "Plastermason",
  "Servant",
  "Barber",
  "Residence",
  "Shepherds",
  "Employment",
  "Fuel Filler",
  "Worker",
  "House Boy",
  "House Wife",
  "RCC Fitter",
  "Clerk",
  "Microbiologist",
  "Teacher",
  "Helper",
  "Hajj Duty",
  "Shuttering",
  "Supervisor",
  "Medical Specialist",
  "Office Secretary",
  "Technician",
  "Butcher",
  "Arabic Food Cook",
  "Agricultural Worker",
  "Service",
  "Studio CAD Designer",
  "Financial Analyst",
  "Cabin Appearance (AIR LINES)",
  "Car Washer",
  "Surveyor",
  "Electrical Technician",
  "Waiter",
  "Nursing Helper",
  "Anesthesia Technician",
  "Construction Worker",
  "Other",
];

export const WP_API_URL = "https://wp.gamcatoken.online/wp-json/wp/v2";

